In [1]:
import pandas as pd
import numpy as np

In [2]:
movie_rating = pd.read_csv('ratings_small.csv')
movie_rating

        userId  movieId  rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
...        ...      ...     ...         ...
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

### select top 57 movies

In [3]:
movie_rating['movieId'].value_counts().head(57)

356     341
296     324
318     311
593     304
260     291
480     274
2571    259
1       247
527     244
589     237
1196    234
110     228
1270    226
608     224
1198    220
2858    220
780     218
1210    217
588     215
457     213
590     202
2959    202
47      201
50      201
364     200
150     200
858     200
4993    200
380     198
592     196
32      196
2762    193
2028    191
1580    190
5952    188
377     180
7153    176
595     176
344     175
4306    174
648     168
1265    165
1721    164
1197    163
3578    161
1097    160
231     158
1240    158
1704    157
367     157
500     153
1036    151
736     150
34      148
1073    148
2716    147
1291    147
Name: movieId, dtype: int64

In [4]:
pop_movie_id = [
356     
,296     
,318     
,593     
,260     
,480     
,2571    
,1       
,527     
,589     
,1196    
,110     
,1270    
,608     
,1198    
,2858    
,780     
,1210    
,588     
,457     
,590     
,2959    
,47      
,50      
,364     
,150     
,858     
,4993    
,380     
,592     
,32      
,2762    
,2028    
,1580    
,5952    
,377     
,7153    
,595     
,344     
,4306    
,648     
,1265    
,1721    
,1197    
,3578    
,1097    
,231     
,1240    
,1704    
,367     
,500     
,1036    
,736     
,34      
,1073    
,2716    
,1291
]

In [7]:
column_headers = ['userId', 'movieId', 'rating', 'timestamp']
tmp_rating = pd.read_csv('tmp_rating.csv', names = column_headers)

tmp_rating

         userId  movieId  rating     timestamp
0           1.0     31.0     0.0  1.422403e+09
1           1.0   1029.0     0.0  1.422403e+09
2           1.0   1061.0     0.0  1.422403e+09
3           1.0   1129.0     0.0  1.422403e+09
4           1.0   1172.0     0.0  1.422403e+09
...         ...      ...     ...           ...
1700063   671.0   6268.0     0.5  1.464390e+09
1700064   671.0   6269.0     0.8  1.464390e+09
1700065   671.0   6365.0     0.8  1.464390e+09
1700066   671.0   6385.0     0.5  1.464390e+09
1700067   671.0   6565.0     0.7  1.464390e+09

[1700068 rows x 4 columns]

In [8]:
pop_movie_id.sort()
pop_movie_id

[1,
 32,
 34,
 47,
 50,
 110,
 150,
 231,
 260,
 296,
 318,
 344,
 356,
 364,
 367,
 377,
 380,
 457,
 480,
 500,
 527,
 588,
 589,
 590,
 592,
 593,
 595,
 608,
 648,
 736,
 780,
 858,
 1036,
 1073,
 1097,
 1196,
 1197,
 1198,
 1210,
 1240,
 1265,
 1270,
 1291,
 1580,
 1704,
 1721,
 2028,
 2571,
 2716,
 2762,
 2858,
 2959,
 3578,
 4306,
 4993,
 5952,
 7153]

In [9]:
movie_rating[movie_rating['userId']==1]

    userId  movieId  rating   timestamp
0        1       31     2.5  1260759144
1        1     1029     3.0  1260759179
2        1     1061     3.0  1260759182
3        1     1129     2.0  1260759185
4        1     1172     4.0  1260759205
5        1     1263     2.0  1260759151
6        1     1287     2.0  1260759187
7        1     1293     2.0  1260759148
8        1     1339     3.5  1260759125
9        1     1343     2.0  1260759131
10       1     1371     2.5  1260759135
11       1     1405     1.0  1260759203
12       1     1953     4.0  1260759191
13       1     2105     4.0  1260759139
14       1     2150     3.0  1260759194
15       1     2193     2.0  1260759198
16       1     2294     2.0  1260759108
17       1     2455     2.5  1260759113
18       1     2968     1.0  1260759200
19       1     3671     3.0  1260759117

In [10]:
tmp_rating_pop = []
for i in tmp_rating.index:
    if tmp_rating.loc[i]['movieId'] in (1,
 32,
 34,
 47,
 50,
 110,
 150,
 231,
 260,
 296,
 318,
 344,
 356,
 364,
 367,
 377,
 380,
 457,
 480,
 500,
 527,
 588,
 589,
 590,
 592,
 593,
 595,
 608,
 648,
 736,
 780,
 858,
 1036,
 1073,
 1097,
 1196,
 1197,
 1198,
 1210,
 1240,
 1265,
 1270,
 1291,
 1580,
 1704,
 1721,
 2028,
 2571,
 2716,
 2762,
 2858,
 2959,
 3578,
 4306,
 4993,
 5952,
 7153):
        tmp_rating_pop.append(tmp_rating.loc[i])

tmp_rating_pop

[userId       2.000000e+00
 movieId      4.700000e+01
 rating       0.000000e+00
 timestamp    1.422403e+09
 Name: 343, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+01
 rating       0.000000e+00
 timestamp    1.422403e+09
 Name: 344, dtype: float64,
 userId       2.000000e+00
 movieId      1.100000e+02
 rating       0.000000e+00
 timestamp    1.422403e+09
 Name: 347, dtype: float64,
 userId       2.000000e+00
 movieId      1.500000e+02
 rating       1.000000e+00
 timestamp    1.422403e+09
 Name: 349, dtype: float64,
 userId       2.000000e+00
 movieId      2.960000e+02
 rating       8.000000e-01
 timestamp    1.422403e+09
 Name: 369, dtype: float64,
 userId       2.000000e+00
 movieId      3.560000e+02
 rating       0.000000e+00
 timestamp    1.422403e+09
 Name: 377, dtype: float64,
 userId       2.000000e+00
 movieId      3.640000e+02
 rating       0.000000e+00
 timestamp    1.422403e+09
 Name: 379, dtype: float64,
 userId       2.000000e+00
 movieId      3.670000e+02
 rating       0.000000e+00
 timestamp    1.422403e+09
 Name: 380, dtype: float64,
 userId       2.000000e+00
 movieId      3.770000e+02
 rating       0.000000e+00
 timestamp    1.422403e+09
 Name: 384, dtype: float64,
 userId       2.000000e+00
 movieId      4.570000e+02
 rating       0.000000e+00
 timestamp    1.422403e+09
 Name: 389, dtype: float64,
 userId       2.000000e+00
 movieId      4.800000e+02
 rating       0.000000e+00
 timestamp    1.422403e+09
 Name: 392, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+02
 rating       0.000000e+00
 timestamp    1.422403e+09
 Name: 395, dtype: float64,
 userId       2.000000e+00
 movieId      5.270000e+02
 rating       0.000000e+00
 timestamp    1.422403e+09
 Name: 399, dtype: float64,
 userId       2.000000e+00
 movieId      5.880000e+02
 rating       6.000000e-01
 timestamp    1.422403e+09
 Name: 408, dtype: float64,
 userId       2.000000e+00
 movieId      5.890000e+02
 rating       0.000000e+00
 timestamp    1.422403e+09
 Name: 409, dtype: float64,
 userId       2.000000e+00
 movieId      5.900000e+02
 rating       1.000000e+00
 timestamp    1.422403e+09
 Name: 410, dtype: float64,
 userId       2.000000e+00
 movieId      5.920000e+02
 rating       1.000000e+00
 timestamp    1.422403e+09
 Name: 411, dtype: float64,
 userId       2.000000e+00
 movieId      5.930000e+02
 rating       0.000000e+00
 timestamp    1.422403e+09
 Name: 412, dtype: float64,
 userId       2.000000e+00
 movieId      4.700000e+01
 rating       0.000000e+00
 timestamp    1.425082e+09
 Name: 419, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+01
 rating       0.000000e+00
 timestamp    1.425082e+09
 Name: 420, dtype: float64,
 userId       2.000000e+00
 movieId      1.100000e+02
 rating       0.000000e+00
 timestamp    1.425082e+09
 Name: 423, dtype: float64,
 userId       2.000000e+00
 movieId      1.500000e+02
 rating       1.000000e+00
 timestamp    1.425082e+09
 Name: 425, dtype: float64,
 userId       2.000000e+00
 movieId      2.960000e+02
 rating       8.000000e-01
 timestamp    1.425082e+09
 Name: 445, dtype: float64,
 userId       2.000000e+00
 movieId      3.560000e+02
 rating       0.000000e+00
 timestamp    1.425082e+09
 Name: 453, dtype: float64,
 userId       2.000000e+00
 movieId      3.640000e+02
 rating       0.000000e+00
 timestamp    1.425082e+09
 Name: 455, dtype: float64,
 userId       2.000000e+00
 movieId      3.670000e+02
 rating       0.000000e+00
 timestamp    1.425082e+09
 Name: 456, dtype: float64,
 userId       2.000000e+00
 movieId      3.770000e+02
 rating       0.000000e+00
 timestamp    1.425082e+09
 Name: 460, dtype: float64,
 userId       2.000000e+00
 movieId      4.570000e+02
 rating       0.000000e+00
 timestamp    1.425082e+09
 Name: 465, dtype: float64,
 userId       2.000000e+00
 movieId      4.800000e+02
 rating       0.000000e+00
 timestamp    1.425082e+09
 Name: 468, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+02
 rating       0.000000e+00
 timestamp    1.425082e+09
 Name: 471, dtype: float64,
 userId       2.000000e+00
 movieId      5.270000e+02
 rating       0.000000e+00
 timestamp    1.425082e+09
 Name: 475, dtype: float64,
 userId       2.000000e+00
 movieId      5.880000e+02
 rating       6.000000e-01
 timestamp    1.425082e+09
 Name: 484, dtype: float64,
 userId       2.000000e+00
 movieId      5.890000e+02
 rating       0.000000e+00
 timestamp    1.425082e+09
 Name: 485, dtype: float64,
 userId       2.000000e+00
 movieId      5.900000e+02
 rating       1.000000e+00
 timestamp    1.425082e+09
 Name: 486, dtype: float64,
 userId       2.000000e+00
 movieId      5.920000e+02
 rating       1.000000e+00
 timestamp    1.425082e+09
 Name: 487, dtype: float64,
 userId       2.000000e+00
 movieId      5.930000e+02
 rating       0.000000e+00
 timestamp    1.425082e+09
 Name: 488, dtype: float64,
 userId       2.000000e+00
 movieId      4.700000e+01
 rating       0.000000e+00
 timestamp    1.427501e+09
 Name: 495, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+01
 rating       0.000000e+00
 timestamp    1.427501e+09
 Name: 496, dtype: float64,
 userId       2.000000e+00
 movieId      1.100000e+02
 rating       8.000000e-01
 timestamp    1.427501e+09
 Name: 499, dtype: float64,
 userId       2.000000e+00
 movieId      1.500000e+02
 rating       1.000000e+00
 timestamp    1.427501e+09
 Name: 501, dtype: float64,
 userId       2.000000e+00
 movieId      2.960000e+02
 rating       8.000000e-01
 timestamp    1.427501e+09
 Name: 521, dtype: float64,
 userId       2.000000e+00
 movieId      3.560000e+02
 rating       0.000000e+00
 timestamp    1.427501e+09
 Name: 529, dtype: float64,
 userId       2.000000e+00
 movieId      3.640000e+02
 rating       0.000000e+00
 timestamp    1.427501e+09
 Name: 531, dtype: float64,
 userId       2.000000e+00
 movieId      3.670000e+02
 rating       0.000000e+00
 timestamp    1.427501e+09
 Name: 532, dtype: float64,
 userId       2.000000e+00
 movieId      3.770000e+02
 rating       0.000000e+00
 timestamp    1.427501e+09
 Name: 536, dtype: float64,
 userId       2.000000e+00
 movieId      4.570000e+02
 rating       6.000000e-01
 timestamp    1.427501e+09
 Name: 541, dtype: float64,
 userId       2.000000e+00
 movieId      4.800000e+02
 rating       0.000000e+00
 timestamp    1.427501e+09
 Name: 544, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+02
 rating       0.000000e+00
 timestamp    1.427501e+09
 Name: 547, dtype: float64,
 userId       2.000000e+00
 movieId      5.270000e+02
 rating       0.000000e+00
 timestamp    1.427501e+09
 Name: 551, dtype: float64,
 userId       2.000000e+00
 movieId      5.880000e+02
 rating       6.000000e-01
 timestamp    1.427501e+09
 Name: 560, dtype: float64,
 userId       2.000000e+00
 movieId      5.890000e+02
 rating       0.000000e+00
 timestamp    1.427501e+09
 Name: 561, dtype: float64,
 userId       2.000000e+00
 movieId      5.900000e+02
 rating       1.000000e+00
 timestamp    1.427501e+09
 Name: 562, dtype: float64,
 userId       2.000000e+00
 movieId      5.920000e+02
 rating       1.000000e+00
 timestamp    1.427501e+09
 Name: 563, dtype: float64,
 userId       2.000000e+00
 movieId      5.930000e+02
 rating       6.000000e-01
 timestamp    1.427501e+09
 Name: 564, dtype: float64,
 userId       2.000000e+00
 movieId      4.700000e+01
 rating       8.000000e-01
 timestamp    1.430176e+09
 Name: 571, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+01
 rating       8.000000e-01
 timestamp    1.430176e+09
 Name: 572, dtype: float64,
 userId       2.000000e+00
 movieId      1.100000e+02
 rating       8.000000e-01
 timestamp    1.430176e+09
 Name: 575, dtype: float64,
 userId       2.000000e+00
 movieId      1.500000e+02
 rating       1.000000e+00
 timestamp    1.430176e+09
 Name: 577, dtype: float64,
 userId       2.000000e+00
 movieId      2.960000e+02
 rating       8.000000e-01
 timestamp    1.430176e+09
 Name: 597, dtype: float64,
 userId       2.000000e+00
 movieId      3.560000e+02
 rating       0.000000e+00
 timestamp    1.430176e+09
 Name: 605, dtype: float64,
 userId       2.000000e+00
 movieId      3.640000e+02
 rating       0.000000e+00
 timestamp    1.430176e+09
 Name: 607, dtype: float64,
 userId       2.000000e+00
 movieId      3.670000e+02
 rating       0.000000e+00
 timestamp    1.430176e+09
 Name: 608, dtype: float64,
 userId       2.000000e+00
 movieId      3.770000e+02
 rating       0.000000e+00
 timestamp    1.430176e+09
 Name: 612, dtype: float64,
 userId       2.000000e+00
 movieId      4.570000e+02
 rating       6.000000e-01
 timestamp    1.430176e+09
 Name: 617, dtype: float64,
 userId       2.000000e+00
 movieId      4.800000e+02
 rating       0.000000e+00
 timestamp    1.430176e+09
 Name: 620, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+02
 rating       0.000000e+00
 timestamp    1.430176e+09
 Name: 623, dtype: float64,
 userId       2.000000e+00
 movieId      5.270000e+02
 rating       0.000000e+00
 timestamp    1.430176e+09
 Name: 627, dtype: float64,
 userId       2.000000e+00
 movieId      5.880000e+02
 rating       6.000000e-01
 timestamp    1.430176e+09
 Name: 636, dtype: float64,
 userId       2.000000e+00
 movieId      5.890000e+02
 rating       0.000000e+00
 timestamp    1.430176e+09
 Name: 637, dtype: float64,
 userId       2.000000e+00
 movieId      5.900000e+02
 rating       1.000000e+00
 timestamp    1.430176e+09
 Name: 638, dtype: float64,
 userId       2.000000e+00
 movieId      5.920000e+02
 rating       1.000000e+00
 timestamp    1.430176e+09
 Name: 639, dtype: float64,
 userId       2.000000e+00
 movieId      5.930000e+02
 rating       6.000000e-01
 timestamp    1.430176e+09
 Name: 640, dtype: float64,
 userId       2.000000e+00
 movieId      4.700000e+01
 rating       8.000000e-01
 timestamp    1.432768e+09
 Name: 647, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+01
 rating       8.000000e-01
 timestamp    1.432768e+09
 Name: 648, dtype: float64,
 userId       2.000000e+00
 movieId      1.100000e+02
 rating       8.000000e-01
 timestamp    1.432768e+09
 Name: 651, dtype: float64,
 userId       2.000000e+00
 movieId      1.500000e+02
 rating       1.000000e+00
 timestamp    1.432768e+09
 Name: 653, dtype: float64,
 userId       2.000000e+00
 movieId      2.960000e+02
 rating       8.000000e-01
 timestamp    1.432768e+09
 Name: 673, dtype: float64,
 userId       2.000000e+00
 movieId      3.560000e+02
 rating       6.000000e-01
 timestamp    1.432768e+09
 Name: 681, dtype: float64,
 userId       2.000000e+00
 movieId      3.640000e+02
 rating       6.000000e-01
 timestamp    1.432768e+09
 Name: 683, dtype: float64,
 userId       2.000000e+00
 movieId      3.670000e+02
 rating       6.000000e-01
 timestamp    1.432768e+09
 Name: 684, dtype: float64,
 userId       2.000000e+00
 movieId      3.770000e+02
 rating       0.000000e+00
 timestamp    1.432768e+09
 Name: 688, dtype: float64,
 userId       2.000000e+00
 movieId      4.570000e+02
 rating       6.000000e-01
 timestamp    1.432768e+09
 Name: 693, dtype: float64,
 userId       2.000000e+00
 movieId      4.800000e+02
 rating       8.000000e-01
 timestamp    1.432768e+09
 Name: 696, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+02
 rating       0.000000e+00
 timestamp    1.432768e+09
 Name: 699, dtype: float64,
 userId       2.000000e+00
 movieId      5.270000e+02
 rating       0.000000e+00
 timestamp    1.432768e+09
 Name: 703, dtype: float64,
 userId       2.000000e+00
 movieId      5.880000e+02
 rating       6.000000e-01
 timestamp    1.432768e+09
 Name: 712, dtype: float64,
 userId       2.000000e+00
 movieId      5.890000e+02
 rating       0.000000e+00
 timestamp    1.432768e+09
 Name: 713, dtype: float64,
 userId       2.000000e+00
 movieId      5.900000e+02
 rating       1.000000e+00
 timestamp    1.432768e+09
 Name: 714, dtype: float64,
 userId       2.000000e+00
 movieId      5.920000e+02
 rating       1.000000e+00
 timestamp    1.432768e+09
 Name: 715, dtype: float64,
 userId       2.000000e+00
 movieId      5.930000e+02
 rating       6.000000e-01
 timestamp    1.432768e+09
 Name: 716, dtype: float64,
 userId       2.000000e+00
 movieId      4.700000e+01
 rating       8.000000e-01
 timestamp    1.435446e+09
 Name: 723, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+01
 rating       8.000000e-01
 timestamp    1.435446e+09
 Name: 724, dtype: float64,
 userId       2.000000e+00
 movieId      1.100000e+02
 rating       8.000000e-01
 timestamp    1.435446e+09
 Name: 727, dtype: float64,
 userId       2.000000e+00
 movieId      1.500000e+02
 rating       1.000000e+00
 timestamp    1.435446e+09
 Name: 729, dtype: float64,
 userId       2.000000e+00
 movieId      2.960000e+02
 rating       8.000000e-01
 timestamp    1.435446e+09
 Name: 749, dtype: float64,
 userId       2.000000e+00
 movieId      3.560000e+02
 rating       6.000000e-01
 timestamp    1.435446e+09
 Name: 757, dtype: float64,
 userId       2.000000e+00
 movieId      3.640000e+02
 rating       6.000000e-01
 timestamp    1.435446e+09
 Name: 759, dtype: float64,
 userId       2.000000e+00
 movieId      3.670000e+02
 rating       6.000000e-01
 timestamp    1.435446e+09
 Name: 760, dtype: float64,
 userId       2.000000e+00
 movieId      3.770000e+02
 rating       0.000000e+00
 timestamp    1.435446e+09
 Name: 764, dtype: float64,
 userId       2.000000e+00
 movieId      4.570000e+02
 rating       6.000000e-01
 timestamp    1.435446e+09
 Name: 769, dtype: float64,
 userId       2.000000e+00
 movieId      4.800000e+02
 rating       8.000000e-01
 timestamp    1.435446e+09
 Name: 772, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+02
 rating       0.000000e+00
 timestamp    1.435446e+09
 Name: 775, dtype: float64,
 userId       2.000000e+00
 movieId      5.270000e+02
 rating       0.000000e+00
 timestamp    1.435446e+09
 Name: 779, dtype: float64,
 userId       2.000000e+00
 movieId      5.880000e+02
 rating       6.000000e-01
 timestamp    1.435446e+09
 Name: 788, dtype: float64,
 userId       2.000000e+00
 movieId      5.890000e+02
 rating       0.000000e+00
 timestamp    1.435446e+09
 Name: 789, dtype: float64,
 userId       2.000000e+00
 movieId      5.900000e+02
 rating       1.000000e+00
 timestamp    1.435446e+09
 Name: 790, dtype: float64,
 userId       2.000000e+00
 movieId      5.920000e+02
 rating       1.000000e+00
 timestamp    1.435446e+09
 Name: 791, dtype: float64,
 userId       2.000000e+00
 movieId      5.930000e+02
 rating       6.000000e-01
 timestamp    1.435446e+09
 Name: 792, dtype: float64,
 userId       2.000000e+00
 movieId      4.700000e+01
 rating       8.000000e-01
 timestamp    1.438038e+09
 Name: 799, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+01
 rating       8.000000e-01
 timestamp    1.438038e+09
 Name: 800, dtype: float64,
 userId       2.000000e+00
 movieId      1.100000e+02
 rating       8.000000e-01
 timestamp    1.438038e+09
 Name: 803, dtype: float64,
 userId       2.000000e+00
 movieId      1.500000e+02
 rating       1.000000e+00
 timestamp    1.438038e+09
 Name: 805, dtype: float64,
 userId       2.000000e+00
 movieId      2.960000e+02
 rating       8.000000e-01
 timestamp    1.438038e+09
 Name: 825, dtype: float64,
 userId       2.000000e+00
 movieId      3.560000e+02
 rating       6.000000e-01
 timestamp    1.438038e+09
 Name: 833, dtype: float64,
 userId       2.000000e+00
 movieId      3.640000e+02
 rating       6.000000e-01
 timestamp    1.438038e+09
 Name: 835, dtype: float64,
 userId       2.000000e+00
 movieId      3.670000e+02
 rating       6.000000e-01
 timestamp    1.438038e+09
 Name: 836, dtype: float64,
 userId       2.000000e+00
 movieId      3.770000e+02
 rating       6.000000e-01
 timestamp    1.438038e+09
 Name: 840, dtype: float64,
 userId       2.000000e+00
 movieId      4.570000e+02
 rating       6.000000e-01
 timestamp    1.438038e+09
 Name: 845, dtype: float64,
 userId       2.000000e+00
 movieId      4.800000e+02
 rating       8.000000e-01
 timestamp    1.438038e+09
 Name: 848, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+02
 rating       8.000000e-01
 timestamp    1.438038e+09
 Name: 851, dtype: float64,
 userId       2.000000e+00
 movieId      5.270000e+02
 rating       8.000000e-01
 timestamp    1.438038e+09
 Name: 855, dtype: float64,
 userId       2.000000e+00
 movieId      5.880000e+02
 rating       6.000000e-01
 timestamp    1.438038e+09
 Name: 864, dtype: float64,
 userId       2.000000e+00
 movieId      5.890000e+02
 rating       1.000000e+00
 timestamp    1.438038e+09
 Name: 865, dtype: float64,
 userId       2.000000e+00
 movieId      5.900000e+02
 rating       1.000000e+00
 timestamp    1.438038e+09
 Name: 866, dtype: float64,
 userId       2.000000e+00
 movieId      5.920000e+02
 rating       1.000000e+00
 timestamp    1.438038e+09
 Name: 867, dtype: float64,
 userId       2.000000e+00
 movieId      5.930000e+02
 rating       6.000000e-01
 timestamp    1.438038e+09
 Name: 868, dtype: float64,
 userId       2.000000e+00
 movieId      4.700000e+01
 rating       8.000000e-01
 timestamp    1.440716e+09
 Name: 875, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+01
 rating       8.000000e-01
 timestamp    1.440716e+09
 Name: 876, dtype: float64,
 userId       2.000000e+00
 movieId      1.100000e+02
 rating       8.000000e-01
 timestamp    1.440716e+09
 Name: 879, dtype: float64,
 userId       2.000000e+00
 movieId      1.500000e+02
 rating       1.000000e+00
 timestamp    1.440716e+09
 Name: 881, dtype: float64,
 userId       2.000000e+00
 movieId      2.960000e+02
 rating       8.000000e-01
 timestamp    1.440716e+09
 Name: 901, dtype: float64,
 userId       2.000000e+00
 movieId      3.560000e+02
 rating       6.000000e-01
 timestamp    1.440716e+09
 Name: 909, dtype: float64,
 userId       2.000000e+00
 movieId      3.640000e+02
 rating       6.000000e-01
 timestamp    1.440716e+09
 Name: 911, dtype: float64,
 userId       2.000000e+00
 movieId      3.670000e+02
 rating       6.000000e-01
 timestamp    1.440716e+09
 Name: 912, dtype: float64,
 userId       2.000000e+00
 movieId      3.770000e+02
 rating       6.000000e-01
 timestamp    1.440716e+09
 Name: 916, dtype: float64,
 userId       2.000000e+00
 movieId      4.570000e+02
 rating       6.000000e-01
 timestamp    1.440716e+09
 Name: 921, dtype: float64,
 userId       2.000000e+00
 movieId      4.800000e+02
 rating       8.000000e-01
 timestamp    1.440716e+09
 Name: 924, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+02
 rating       8.000000e-01
 timestamp    1.440716e+09
 Name: 927, dtype: float64,
 userId       2.000000e+00
 movieId      5.270000e+02
 rating       8.000000e-01
 timestamp    1.440716e+09
 Name: 931, dtype: float64,
 userId       2.000000e+00
 movieId      5.880000e+02
 rating       6.000000e-01
 timestamp    1.440716e+09
 Name: 940, dtype: float64,
 userId       2.000000e+00
 movieId      5.890000e+02
 rating       1.000000e+00
 timestamp    1.440716e+09
 Name: 941, dtype: float64,
 userId       2.000000e+00
 movieId      5.900000e+02
 rating       1.000000e+00
 timestamp    1.440716e+09
 Name: 942, dtype: float64,
 userId       2.000000e+00
 movieId      5.920000e+02
 rating       1.000000e+00
 timestamp    1.440716e+09
 Name: 943, dtype: float64,
 userId       2.000000e+00
 movieId      5.930000e+02
 rating       6.000000e-01
 timestamp    1.440716e+09
 Name: 944, dtype: float64,
 userId       2.000000e+00
 movieId      4.700000e+01
 rating       8.000000e-01
 timestamp    1.443395e+09
 Name: 951, dtype: float64,
 userId       2.000000e+00
 movieId      5.000000e+01
 rating       8.000000e-01
 timestamp    1.443395e+09
 Name: 952, dtype: float64,
 userId       2.000000e+00
 movieId      1.100000e+02
 rating       8.000000e-01
 timestamp    1.443395e+09
 Name: 955, dtype: float64,

In [11]:
A = pd.DataFrame(tmp_rating_pop)
A

         userId  movieId  rating     timestamp
343         2.0     47.0     0.0  1.422403e+09
344         2.0     50.0     0.0  1.422403e+09
347         2.0    110.0     0.0  1.422403e+09
349         2.0    150.0     1.0  1.422403e+09
369         2.0    296.0     0.8  1.422403e+09
...         ...      ...     ...           ...
1700015   671.0   2858.0     0.8  1.464390e+09
1700017   671.0   2959.0     0.8  1.464390e+09
1700039   671.0   4306.0     1.0  1.464390e+09
1700046   671.0   4993.0     1.0  1.464390e+09
1700058   671.0   5952.0     1.0  1.464390e+09

[196197 rows x 4 columns]

### save the data for BERT4Rec, SASRec, TiSASRec, MEANTIME for CASE5

In [12]:
A.to_csv("ratings5.csv", header= None, index=False)

### Dataset for CASE6 (all rating=1 setting, except rating=0)

In [13]:
#tmp_rating_1 = []
tmp_rating_1 = pd.read_csv("ratings5.csv", header= None)
#tmp_rating_1
tmp_rating_1.columns = ['userId', 'movieId', 'rating', 'timestamp']
#tmp_rating_1

for i in tmp_rating_1.index:
    if tmp_rating_1.loc[i]['rating'] > 0:
        tmp_rating_1.loc[i]['rating'] = 1
#    tmp_rating_1.append(tmp_rating.loc[i])
#    
tmp_rating_1

        userId  movieId  rating     timestamp
0          2.0     47.0     0.0  1.422403e+09
1          2.0     50.0     0.0  1.422403e+09
2          2.0    110.0     0.0  1.422403e+09
3          2.0    150.0     1.0  1.422403e+09
4          2.0    296.0     1.0  1.422403e+09
...        ...      ...     ...           ...
196192   671.0   2858.0     1.0  1.464390e+09
196193   671.0   2959.0     1.0  1.464390e+09
196194   671.0   4306.0     1.0  1.464390e+09
196195   671.0   4993.0     1.0  1.464390e+09
196196   671.0   5952.0     1.0  1.464390e+09

[196197 rows x 4 columns]

In [14]:
B = pd.DataFrame(tmp_rating_1)
B

        userId  movieId  rating     timestamp
0          2.0     47.0     0.0  1.422403e+09
1          2.0     50.0     0.0  1.422403e+09
2          2.0    110.0     0.0  1.422403e+09
3          2.0    150.0     1.0  1.422403e+09
4          2.0    296.0     1.0  1.422403e+09
...        ...      ...     ...           ...
196192   671.0   2858.0     1.0  1.464390e+09
196193   671.0   2959.0     1.0  1.464390e+09
196194   671.0   4306.0     1.0  1.464390e+09
196195   671.0   4993.0     1.0  1.464390e+09
196196   671.0   5952.0     1.0  1.464390e+09

[196197 rows x 4 columns]

### save the data for BERT4Rec, SASRec, TiSASRec, MEANTIME for CASE6

In [15]:
B.to_csv("ratings8.csv", header= None, index=False)

In [16]:
A[A['userId']==1]

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []

### this is for CSE, pivotting the data

In [17]:
mr_small = A.pivot(index=['userId','timestamp'], columns='movieId', values='rating')
mr_small

movieId              1.0     32.0    34.0    47.0    50.0    110.0   150.0   \
userId timestamp
2.0    1.422403e+09     NaN     NaN     NaN     0.0     0.0     0.0     1.0
       1.425082e+09     NaN     NaN     NaN     0.0     0.0     0.0     1.0
       1.427501e+09     NaN     NaN     NaN     0.0     0.0     0.8     1.0
       1.430176e+09     NaN     NaN     NaN     0.8     0.8     0.8     1.0
       1.432768e+09     NaN     NaN     NaN     0.8     0.8     0.8     1.0
...                     ...     ...     ...     ...     ...     ...     ...
671.0  1.453939e+09     1.0     NaN     NaN     NaN     0.9     NaN     NaN
       1.456618e+09     1.0     NaN     NaN     NaN     0.9     NaN     NaN
       1.459120e+09     1.0     NaN     NaN     NaN     0.9     NaN     NaN
       1.461798e+09     1.0     NaN     NaN     NaN     0.9     NaN     NaN
       1.464390e+09     1.0     NaN     NaN     NaN     0.9     NaN     NaN

movieId              231.0   260.0   296.0   ...  2571.0  2716.0  2762.0  \
userId timestamp                             ...
2.0    1.422403e+09     NaN     NaN     0.8  ...     NaN     NaN     NaN
       1.425082e+09     NaN     NaN     0.8  ...     NaN     NaN     NaN
       1.427501e+09     NaN     NaN     0.8  ...     NaN     NaN     NaN
       1.430176e+09     NaN     NaN     0.8  ...     NaN     NaN     NaN
       1.432768e+09     NaN     NaN     0.8  ...     NaN     NaN     NaN
...                     ...     ...     ...  ...     ...     ...     ...
671.0  1.453939e+09     NaN     1.0     0.8  ...     0.9     NaN     0.8
       1.456618e+09     NaN     1.0     0.8  ...     0.9     NaN     0.8
       1.459120e+09     NaN     1.0     0.8  ...     0.9     NaN     0.8
       1.461798e+09     NaN     1.0     0.8  ...     0.9     NaN     0.8
       1.464390e+09     NaN     1.0     0.8  ...     0.9     NaN     0.8

movieId              2858.0  2959.0  3578.0  4306.0  4993.0  5952.0  7153.0
userId timestamp
2.0    1.422403e+09     NaN     NaN     NaN     NaN     NaN     NaN     NaN
       1.425082e+09     NaN     NaN     NaN     NaN     NaN     NaN     NaN
       1.427501e+09     NaN     NaN     NaN     NaN     NaN     NaN     NaN
       1.430176e+09     NaN     NaN     NaN     NaN     NaN     NaN     NaN
       1.432768e+09     NaN     NaN     NaN     NaN     NaN     NaN     NaN
...                     ...     ...     ...     ...     ...     ...     ...
671.0  1.453939e+09     0.8     0.8     NaN     1.0     1.0     1.0     NaN
       1.456618e+09     0.8     0.8     NaN     1.0     1.0     1.0     NaN
       1.459120e+09     0.8     0.8     NaN     1.0     1.0     1.0     NaN
       1.461798e+09     0.8     0.8     NaN     1.0     1.0     1.0     NaN
       1.464390e+09     0.8     0.8     NaN     1.0     1.0     1.0     NaN

[10931 rows x 57 columns]

In [18]:
mr_small = mr_small.fillna(0)
mr_small

movieId              1.0     32.0    34.0    47.0    50.0    110.0   150.0   \
userId timestamp
2.0    1.422403e+09     0.0     0.0     0.0     0.0     0.0     0.0     1.0
       1.425082e+09     0.0     0.0     0.0     0.0     0.0     0.0     1.0
       1.427501e+09     0.0     0.0     0.0     0.0     0.0     0.8     1.0
       1.430176e+09     0.0     0.0     0.0     0.8     0.8     0.8     1.0
       1.432768e+09     0.0     0.0     0.0     0.8     0.8     0.8     1.0
...                     ...     ...     ...     ...     ...     ...     ...
671.0  1.453939e+09     1.0     0.0     0.0     0.0     0.9     0.0     0.0
       1.456618e+09     1.0     0.0     0.0     0.0     0.9     0.0     0.0
       1.459120e+09     1.0     0.0     0.0     0.0     0.9     0.0     0.0
       1.461798e+09     1.0     0.0     0.0     0.0     0.9     0.0     0.0
       1.464390e+09     1.0     0.0     0.0     0.0     0.9     0.0     0.0

movieId              231.0   260.0   296.0   ...  2571.0  2716.0  2762.0  \
userId timestamp                             ...
2.0    1.422403e+09     0.0     0.0     0.8  ...     0.0     0.0     0.0
       1.425082e+09     0.0     0.0     0.8  ...     0.0     0.0     0.0
       1.427501e+09     0.0     0.0     0.8  ...     0.0     0.0     0.0
       1.430176e+09     0.0     0.0     0.8  ...     0.0     0.0     0.0
       1.432768e+09     0.0     0.0     0.8  ...     0.0     0.0     0.0
...                     ...     ...     ...  ...     ...     ...     ...
671.0  1.453939e+09     0.0     1.0     0.8  ...     0.9     0.0     0.8
       1.456618e+09     0.0     1.0     0.8  ...     0.9     0.0     0.8
       1.459120e+09     0.0     1.0     0.8  ...     0.9     0.0     0.8
       1.461798e+09     0.0     1.0     0.8  ...     0.9     0.0     0.8
       1.464390e+09     0.0     1.0     0.8  ...     0.9     0.0     0.8

movieId              2858.0  2959.0  3578.0  4306.0  4993.0  5952.0  7153.0
userId timestamp
2.0    1.422403e+09     0.0     0.0     0.0     0.0     0.0     0.0     0.0
       1.425082e+09     0.0     0.0     0.0     0.0     0.0     0.0     0.0
       1.427501e+09     0.0     0.0     0.0     0.0     0.0     0.0     0.0
       1.430176e+09     0.0     0.0     0.0     0.0     0.0     0.0     0.0
       1.432768e+09     0.0     0.0     0.0     0.0     0.0     0.0     0.0
...                     ...     ...     ...     ...     ...     ...     ...
671.0  1.453939e+09     0.8     0.8     0.0     1.0     1.0     1.0     0.0
       1.456618e+09     0.8     0.8     0.0     1.0     1.0     1.0     0.0
       1.459120e+09     0.8     0.8     0.0     1.0     1.0     1.0     0.0
       1.461798e+09     0.8     0.8     0.0     1.0     1.0     1.0     0.0
       1.464390e+09     0.8     0.8     0.0     1.0     1.0     1.0     0.0

[10931 rows x 57 columns]

In [19]:
mr_small = mr_small.reset_index()
mr_small

movieId,userId,timestamp,1.0,32.0,34.0,47.0,50.0,110.0,150.0,231.0,...,2571.0,2716.0,2762.0,2858.0,2959.0,3578.0,4306.0,4993.0,5952.0,7153.0
0,2.0,1.422403e+09,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,1.425082e+09,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.0,1.427501e+09,0.0,0.0,0.0,0.0,0.0,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.0,1.430176e+09,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2.0,1.432768e+09,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10926,671.0,1.453939e+09,1.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,...,0.9,0.0,0.8,0.8,0.8,0.0,1.0,1.0,1.0,0.0
10927,671.0,1.456618e+09,1.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,...,0.9,0.0,0.8,0.8,0.8,0.0,1.0,1.0,1.0,0.0
10928,671.0,1.459120e+09,1.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,...,0.9,0.0,0.8,0.8,0.8,0.0,1.0,1.0,1.0,0.0
10929,671.0,1.461798e+09,1.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,...,0.9,0.0,0.8,0.8,0.8,0.0,1.0,1.0,1.0,0.0
10930,671.0,1.464390e+09,1.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,...,0.9,0.0,0.8,0.8,0.8,0.0,1.0,1.0,1.0,0.0

In [20]:
mr_small.sort_values('userId')

movieId,userId,timestamp,1.0,32.0,34.0,47.0,50.0,110.0,150.0,231.0,...,2571.0,2716.0,2762.0,2858.0,2959.0,3578.0,4306.0,4993.0,5952.0,7153.0
0,2.0,1.422403e+09,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2.0,1.464390e+09,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2.0,1.461798e+09,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2.0,1.459120e+09,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2.0,1.456618e+09,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10915,671.0,1.425082e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.8,0.0,0.0,1.0,1.0,1.0,0.0
10914,671.0,1.422403e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.8,0.0,0.0,0.0,0.0,1.0,0.0
10929,671.0,1.461798e+09,1.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,...,0.9,0.0,0.8,0.8,0.8,0.0,1.0,1.0,1.0,0.0
10921,671.0,1.440716e+09,1.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,...,0.9,0.0,0.8,0.8,0.8,0.0,1.0,1.0,1.0,0.0
10930,671.0,1.464390e+09,1.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,...,0.9,0.0,0.8,0.8,0.8,0.0,1.0,1.0,1.0,0.0

### manipulate timestamp range from 20150128 to 20160528

In [21]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
    
#print(type(month_s))\n",
#print(month_s)\n",
tmp = ''
j=0
for i in mr_small['userId']:
 
    #after_one_month = month_s
    if tmp == i:

        tmp_month = tmp_month + relativedelta(months=1)
        #print(\"1 : \" ,mr_small.loc[[j],['timestamp']])
        mr_small.loc[[j],['timestamp']] = tmp_month
        tmp = i
        #print(\"1 : \" ,tmp_month)
        #print(\"1 mr_small : \" ,mr_small)
        #timestamp = month_s
    else:
        month_s = '2015-01-28'
        month_s = datetime.strptime(month_s, '%Y-%m-%d').date()
        #print(\"2 : \" ,mr_small.loc[i,'timestamp'])
        mr_small.loc[[j],['timestamp']] = month_s
        tmp_month = month_s
        tmp = i
        #print(\"2 : \" ,tmp_month)
        #print(\"2 mr_small : \" ,mr_small)
    j += 1
#mr_small['userId']

In [22]:
mr_small[:20][:67]

movieId,userId,timestamp,1.0,32.0,34.0,47.0,50.0,110.0,150.0,231.0,...,2571.0,2716.0,2762.0,2858.0,2959.0,3578.0,4306.0,4993.0,5952.0,7153.0
0,2.0,2015-01-28,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,2015-02-28,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.0,2015-03-28,0.0,0.0,0.0,0.0,0.0,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.0,2015-04-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2.0,2015-05-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2.0,2015-06-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2.0,2015-07-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2.0,2015-08-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2.0,2015-09-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2.0,2015-10-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2.0,2015-11-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2.0,2015-12-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2.0,2016-01-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2.0,2016-02-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2.0,2016-03-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2.0,2016-04-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2.0,2016-05-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,3.0,2015-01-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
18,3.0,2015-02-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
19,3.0,2015-03-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [23]:
mr_small[:20]

movieId,userId,timestamp,1.0,32.0,34.0,47.0,50.0,110.0,150.0,231.0,...,2571.0,2716.0,2762.0,2858.0,2959.0,3578.0,4306.0,4993.0,5952.0,7153.0
0,2.0,2015-01-28,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,2015-02-28,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.0,2015-03-28,0.0,0.0,0.0,0.0,0.0,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.0,2015-04-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2.0,2015-05-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2.0,2015-06-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2.0,2015-07-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2.0,2015-08-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2.0,2015-09-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2.0,2015-10-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2.0,2015-11-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2.0,2015-12-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2.0,2016-01-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2.0,2016-02-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2.0,2016-03-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2.0,2016-04-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2.0,2016-05-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,3.0,2015-01-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
18,3.0,2015-02-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
19,3.0,2015-03-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [24]:
mr_small

movieId,userId,timestamp,1.0,32.0,34.0,47.0,50.0,110.0,150.0,231.0,...,2571.0,2716.0,2762.0,2858.0,2959.0,3578.0,4306.0,4993.0,5952.0,7153.0
0,2.0,2015-01-28,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,2015-02-28,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.0,2015-03-28,0.0,0.0,0.0,0.0,0.0,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.0,2015-04-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2.0,2015-05-28,0.0,0.0,0.0,0.8,0.8,0.8,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10926,671.0,2016-01-28,1.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,...,0.9,0.0,0.8,0.8,0.8,0.0,1.0,1.0,1.0,0.0
10927,671.0,2016-02-28,1.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,...,0.9,0.0,0.8,0.8,0.8,0.0,1.0,1.0,1.0,0.0
10928,671.0,2016-03-28,1.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,...,0.9,0.0,0.8,0.8,0.8,0.0,1.0,1.0,1.0,0.0
10929,671.0,2016-04-28,1.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,...,0.9,0.0,0.8,0.8,0.8,0.0,1.0,1.0,1.0,0.0
10930,671.0,2016-05-28,1.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,...,0.9,0.0,0.8,0.8,0.8,0.0,1.0,1.0,1.0,0.0

In [25]:
mr_small.to_csv("prep_rating5.csv", index=False)

### save the data for CSE for CASE5

In [26]:
mr_small = B.pivot(index=['userId','timestamp'], columns='movieId', values='rating')
mr_small

movieId              1.0     32.0    34.0    47.0    50.0    110.0   150.0   \
userId timestamp
2.0    1.422403e+09     NaN     NaN     NaN     0.0     0.0     0.0     1.0
       1.425082e+09     NaN     NaN     NaN     0.0     0.0     0.0     1.0
       1.427501e+09     NaN     NaN     NaN     0.0     0.0     1.0     1.0
       1.430176e+09     NaN     NaN     NaN     1.0     1.0     1.0     1.0
       1.432768e+09     NaN     NaN     NaN     1.0     1.0     1.0     1.0
...                     ...     ...     ...     ...     ...     ...     ...
671.0  1.453939e+09     1.0     NaN     NaN     NaN     1.0     NaN     NaN
       1.456618e+09     1.0     NaN     NaN     NaN     1.0     NaN     NaN
       1.459120e+09     1.0     NaN     NaN     NaN     1.0     NaN     NaN
       1.461798e+09     1.0     NaN     NaN     NaN     1.0     NaN     NaN
       1.464390e+09     1.0     NaN     NaN     NaN     1.0     NaN     NaN

movieId              231.0   260.0   296.0   ...  2571.0  2716.0  2762.0  \
userId timestamp                             ...
2.0    1.422403e+09     NaN     NaN     1.0  ...     NaN     NaN     NaN
       1.425082e+09     NaN     NaN     1.0  ...     NaN     NaN     NaN
       1.427501e+09     NaN     NaN     1.0  ...     NaN     NaN     NaN
       1.430176e+09     NaN     NaN     1.0  ...     NaN     NaN     NaN
       1.432768e+09     NaN     NaN     1.0  ...     NaN     NaN     NaN
...                     ...     ...     ...  ...     ...     ...     ...
671.0  1.453939e+09     NaN     1.0     1.0  ...     1.0     NaN     1.0
       1.456618e+09     NaN     1.0     1.0  ...     1.0     NaN     1.0
       1.459120e+09     NaN     1.0     1.0  ...     1.0     NaN     1.0
       1.461798e+09     NaN     1.0     1.0  ...     1.0     NaN     1.0
       1.464390e+09     NaN     1.0     1.0  ...     1.0     NaN     1.0

movieId              2858.0  2959.0  3578.0  4306.0  4993.0  5952.0  7153.0
userId timestamp
2.0    1.422403e+09     NaN     NaN     NaN     NaN     NaN     NaN     NaN
       1.425082e+09     NaN     NaN     NaN     NaN     NaN     NaN     NaN
       1.427501e+09     NaN     NaN     NaN     NaN     NaN     NaN     NaN
       1.430176e+09     NaN     NaN     NaN     NaN     NaN     NaN     NaN
       1.432768e+09     NaN     NaN     NaN     NaN     NaN     NaN     NaN
...                     ...     ...     ...     ...     ...     ...     ...
671.0  1.453939e+09     1.0     1.0     NaN     1.0     1.0     1.0     NaN
       1.456618e+09     1.0     1.0     NaN     1.0     1.0     1.0     NaN
       1.459120e+09     1.0     1.0     NaN     1.0     1.0     1.0     NaN
       1.461798e+09     1.0     1.0     NaN     1.0     1.0     1.0     NaN
       1.464390e+09     1.0     1.0     NaN     1.0     1.0     1.0     NaN

[10931 rows x 57 columns]

In [27]:
mr_small = mr_small.fillna(0)
mr_small

movieId              1.0     32.0    34.0    47.0    50.0    110.0   150.0   \
userId timestamp
2.0    1.422403e+09     0.0     0.0     0.0     0.0     0.0     0.0     1.0
       1.425082e+09     0.0     0.0     0.0     0.0     0.0     0.0     1.0
       1.427501e+09     0.0     0.0     0.0     0.0     0.0     1.0     1.0
       1.430176e+09     0.0     0.0     0.0     1.0     1.0     1.0     1.0
       1.432768e+09     0.0     0.0     0.0     1.0     1.0     1.0     1.0
...                     ...     ...     ...     ...     ...     ...     ...
671.0  1.453939e+09     1.0     0.0     0.0     0.0     1.0     0.0     0.0
       1.456618e+09     1.0     0.0     0.0     0.0     1.0     0.0     0.0
       1.459120e+09     1.0     0.0     0.0     0.0     1.0     0.0     0.0
       1.461798e+09     1.0     0.0     0.0     0.0     1.0     0.0     0.0
       1.464390e+09     1.0     0.0     0.0     0.0     1.0     0.0     0.0

movieId              231.0   260.0   296.0   ...  2571.0  2716.0  2762.0  \
userId timestamp                             ...
2.0    1.422403e+09     0.0     0.0     1.0  ...     0.0     0.0     0.0
       1.425082e+09     0.0     0.0     1.0  ...     0.0     0.0     0.0
       1.427501e+09     0.0     0.0     1.0  ...     0.0     0.0     0.0
       1.430176e+09     0.0     0.0     1.0  ...     0.0     0.0     0.0
       1.432768e+09     0.0     0.0     1.0  ...     0.0     0.0     0.0
...                     ...     ...     ...  ...     ...     ...     ...
671.0  1.453939e+09     0.0     1.0     1.0  ...     1.0     0.0     1.0
       1.456618e+09     0.0     1.0     1.0  ...     1.0     0.0     1.0
       1.459120e+09     0.0     1.0     1.0  ...     1.0     0.0     1.0
       1.461798e+09     0.0     1.0     1.0  ...     1.0     0.0     1.0
       1.464390e+09     0.0     1.0     1.0  ...     1.0     0.0     1.0

movieId              2858.0  2959.0  3578.0  4306.0  4993.0  5952.0  7153.0
userId timestamp
2.0    1.422403e+09     0.0     0.0     0.0     0.0     0.0     0.0     0.0
       1.425082e+09     0.0     0.0     0.0     0.0     0.0     0.0     0.0
       1.427501e+09     0.0     0.0     0.0     0.0     0.0     0.0     0.0
       1.430176e+09     0.0     0.0     0.0     0.0     0.0     0.0     0.0
       1.432768e+09     0.0     0.0     0.0     0.0     0.0     0.0     0.0
...                     ...     ...     ...     ...     ...     ...     ...
671.0  1.453939e+09     1.0     1.0     0.0     1.0     1.0     1.0     0.0
       1.456618e+09     1.0     1.0     0.0     1.0     1.0     1.0     0.0
       1.459120e+09     1.0     1.0     0.0     1.0     1.0     1.0     0.0
       1.461798e+09     1.0     1.0     0.0     1.0     1.0     1.0     0.0
       1.464390e+09     1.0     1.0     0.0     1.0     1.0     1.0     0.0

[10931 rows x 57 columns]

In [28]:
mr_small = mr_small.reset_index()
mr_small

movieId,userId,timestamp,1.0,32.0,34.0,47.0,50.0,110.0,150.0,231.0,...,2571.0,2716.0,2762.0,2858.0,2959.0,3578.0,4306.0,4993.0,5952.0,7153.0
0,2.0,1.422403e+09,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,1.425082e+09,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.0,1.427501e+09,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.0,1.430176e+09,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2.0,1.432768e+09,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10926,671.0,1.453939e+09,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0
10927,671.0,1.456618e+09,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0
10928,671.0,1.459120e+09,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0
10929,671.0,1.461798e+09,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0
10930,671.0,1.464390e+09,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0

In [29]:
mr_small.sort_values('userId')

movieId,userId,timestamp,1.0,32.0,34.0,47.0,50.0,110.0,150.0,231.0,...,2571.0,2716.0,2762.0,2858.0,2959.0,3578.0,4306.0,4993.0,5952.0,7153.0
0,2.0,1.422403e+09,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2.0,1.464390e+09,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2.0,1.461798e+09,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2.0,1.459120e+09,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2.0,1.456618e+09,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10915,671.0,1.425082e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0
10914,671.0,1.422403e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
10929,671.0,1.461798e+09,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0
10921,671.0,1.440716e+09,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0
10930,671.0,1.464390e+09,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0

### manipulate timestamp range from 20150128 to 20160528

In [30]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
    
#print(type(month_s))\n",
#print(month_s)\n",
tmp = ''
j=0
for i in mr_small['userId']:
 
    #after_one_month = month_s
    if tmp == i:

        tmp_month = tmp_month + relativedelta(months=1)
        #print(\"1 : \" ,mr_small.loc[[j],['timestamp']])
        mr_small.loc[[j],['timestamp']] = tmp_month
        tmp = i
        #print(\"1 : \" ,tmp_month)
        #print(\"1 mr_small : \" ,mr_small)
        #timestamp = month_s
    else:
        month_s = '2015-01-28'
        month_s = datetime.strptime(month_s, '%Y-%m-%d').date()
        #print(\"2 : \" ,mr_small.loc[i,'timestamp'])
        mr_small.loc[[j],['timestamp']] = month_s
        tmp_month = month_s
        tmp = i
        #print(\"2 : \" ,tmp_month)
        #print(\"2 mr_small : \" ,mr_small)
    j += 1
#mr_small['userId']

In [31]:
mr_small[:20][:67]

movieId,userId,timestamp,1.0,32.0,34.0,47.0,50.0,110.0,150.0,231.0,...,2571.0,2716.0,2762.0,2858.0,2959.0,3578.0,4306.0,4993.0,5952.0,7153.0
0,2.0,2015-01-28,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,2015-02-28,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.0,2015-03-28,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.0,2015-04-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2.0,2015-05-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2.0,2015-06-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2.0,2015-07-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2.0,2015-08-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2.0,2015-09-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2.0,2015-10-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2.0,2015-11-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2.0,2015-12-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2.0,2016-01-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2.0,2016-02-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2.0,2016-03-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2.0,2016-04-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2.0,2016-05-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,3.0,2015-01-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
18,3.0,2015-02-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
19,3.0,2015-03-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [32]:
mr_small

movieId,userId,timestamp,1.0,32.0,34.0,47.0,50.0,110.0,150.0,231.0,...,2571.0,2716.0,2762.0,2858.0,2959.0,3578.0,4306.0,4993.0,5952.0,7153.0
0,2.0,2015-01-28,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,2015-02-28,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.0,2015-03-28,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.0,2015-04-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2.0,2015-05-28,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10926,671.0,2016-01-28,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0
10927,671.0,2016-02-28,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0
10928,671.0,2016-03-28,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0
10929,671.0,2016-04-28,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0
10930,671.0,2016-05-28,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0

### save the data for CSE for CASE6

In [33]:
mr_small.to_csv("prep_rating8.csv", index=False)